import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import useAppContext from "./../hooks/appContextHook"
import Loading from "../components/Loading/Loading"

const Home: NextPage = () => {
  const { setLoading, loading } = useAppContext()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <button type="button" onClick={() => setLoading(true)}>Show loading</button>
      </main>
      { loading && <Loading /> }
    </div>
  )
}

export default Home
